[package]
name = "ecdsa"
version = "8.0.0"
description = "Library to sign and verify with ECDSA"
repository = "https://github.com/edjCase/motoko_ecdsa"
keywords = [
  "ecdsa",
  "signature",
  "verify",
  "key",
  "public",
  "private",
  "curve",
  "cryptography",
]
license = "Apache-2.0"

[dependencies]
"sha2@0" = "0.1.14"
"asn1@3" = "3.1.0"
"xtended-numbers@2" = "2.3.0"
"base-x-encoder@2" = "2.1.0"
"core@2" = "2.5.0"
"buffer@0" = "0.1.0"
"xtended-iter@1" = "1.1.0"

[dev-dependencies]
test = "2.1.1"
bench-helper = "0.0.3"

[toolchain]
moc = "1.7.0"
pocket-ic = "9.0.3"

